spring:
  application:
    name: consul-consumer
server:
  port: 8506
  cloud:
    consul:
      host: 192.168.31.25
      port: 8500
      discovery:
        registry: false
logging:
  level:
    com.example.consulconsumer: DEBUG
feign:
  hystrix:
    enabled: true
turbine:
#  app-config: consul-consumer,consul-consumer2
  app-config: consul-consumer
  aggregator:
    cluster-config: default
  cluster-name-expression: new String("default")