server:
  port: 8181
  tomcat:
    mbeanregistry:
      enabled: true
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@192.168.31.23:1521/pdb1
    username: pdbadmin
    password: oracle
    hikari:
      minimum-idle: 3
      maximum-pool-size: 3
  thymeleaf:
    cache: false
    encoding: utf-8
  jmx:
    enabled: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true