server:
  port: 8506
spring:
  application:
    name: consul-consumer
  cloud:
    consul:
      host: 192.168.31.25
      port: 8500
      discovery:
        registry: false
logging:
  level:
    com.example.consulconsumer: DEBUG
