spring.jpa.hibernate.ddl-auto: none
spring.datasource.url: jdbc:mysql://localhost:3306/chapter15
spring.datasource.username: root
spring.datasource.password: oracle
opentracing:
  jaeger:
    enabled: true
    service-name: customized-tracer
    const-sampler:
      decision: true # decision等于true表示全部上报，decision等于false表示一个也不上报
#    probabilistic-sampler:
#      sampling-rate: 1 # 0.1表示设置采用率为10%,1表示设置采用率为100%
#    rate-limiting-sampler:
#      max-traces-per-second: 1 # 每秒只采样一个
    udp-sender:
      host: localhost
      port: 6831
#    http-sender:
#      url: http://localhost:9411/api/traces
    log-spans: false
